[package]
name = "speakeasy-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
libc.workspace = true
libloading.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros", "sync"] }

[target.'cfg(target_os = "macos")'.dependencies]
arboard.workspace = true
raw-window-handle.workspace = true
block2.workspace = true
core-foundation.workspace = true
core-graphics.workspace = true
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
